export const dungeonNames = [
    "Echoing Depths",
    "Whispering Caves",
    "Frostfire Hollow",
    "Shadowed Keep",
    "Lost Tombs",
    "Grimwood Labyrinth",
    "Dragon's Descent",
    "Time Shattered Tower",
    "Oracle's Sanctum",
    "Sunken Ruins",
    "Voyager's Grotto",
    "Veiled Bastion",
    "Screaming Chasm",
    "Eternal Night Crypt",
    "Arcane Asylum",
    "Starfall Pit",
    "Harmony Haunt",
    "Silent Guardian Ruins",
    "Forbidden Fortress",
    "Wraith's Chasm",
    "Mirror Maze",
    "Obsidian Cells",
    "Desolate Dungeons",
    "Broken Chain Bastion",
    "Luminous Lair",
    "Gorgon's Grotto",
    "Sentinel's Stone",
    "Tenebrous Temple",
    "Dreamless Den",
    "Screaming Sand Citadel",
    "Revenant's Realm",
    "Bloodmoon Depths",
    "Shadowed Prison",
    "Forgotten Fane",
    "Crying Caverns",
    "Vanished Vault",
    "Nightmare Nexus",
    "Silver Sanctuary",
    "Enigma Hall",
    "Hollowed Haven",
    "Infernal Inn",
    "Unseen Undercroft",
    "Mournful Mausoleum",
    "Phantom Palace",
    "Dancing Djinn Delves",
    "Oasis of Opulence",
    "Buried Bastille",
    "Celestial Crypt",
    "Silent Shrine",
    "Last Lament Labyrinth",
    "Twilight Hollow",
    "Mystic Grotto",
    "Ruins of the Ancients",
    "Forbidden Depths",
    "Sunset Citadel",
    "Whispering Forest Ruins",
    "Stoneclaw Caves",
    "Moonlit Labyrinth",
    "Towers of Desolation",
    "Sable Fortress",
    "Dreadful Den",
    "Dragonbone Catacombs",
    "Ebon Keep",
    "Sunken Sanctuary",
    "Fallen Kingdom Ruins",
    "Ghostly Grove",
    "Deserted Bastion",
    "Temple of Echoes",
    "Lost Voyager's Respite",
    "Darkwater Caves",
    "Tempest Spire",
    "Midnight Maze",
    "Silent Halls",
    "Grimwood Depths",
    "Starshade Tower",
    "Haunted Tombs",
    "Veil of Night Crypt",
    "Rune-etched Grotto",
    "Windswept Ruins",
    "Mist-shrouded Fortress",
    "Solar Flare Bastion",
    "Ghostfire Crypt",
    "Frozen Undercroft",
    "Guardian's Respite",
    "Dusktide Dungeon",
    "Mystic Marshlands",
    "Lost Oasis",
    "Shattered Citadel",
    "Emerald Isle Ruins",
    "Dreadfang Den",
    "Sunstone Spire",
    "Lost Legends Lair",
    "Ravaged Temple",
    "Eldritch Enclave",
    "Gilded Catacombs",
    "Moonshadow Maze",
    "Ocean's Descent",
    "Guardians of the Void",
    "Crimson Caverns",
    "Realm of Lost Souls",
    "Temple of the Forgotten",
    "Riftshadow Ruins",
    "Ethereal Hollows",
    "Darkened Depths",
    "Frostbite Fortress",
    "Ocean's End Grotto",
    "Ruins of Solitude",
    "Golden Citadel",
    "Deserted Chambers",
    "Petrified Forest Cave",
    "Towers of Silence",
    "Moonfall Keep",
    "Eclipse Enclave",
    "Stormpeak Bastion",
    "Lost Horizon Labyrinth",
    "Firebrand Crypts",
    "Netherworld Nexus",
    "Sunfire Spire",
    "Mossy Stone Ruins",
    "Realm of the Fallen",
    "Duskwood Dungeon",
    "Ghostpeak Tower",
    "Cerulean Caves",
    "Starlight Sanctuary",
    "Eldertree Enclave",
    "Cave of Echoes",
    "Lost Kingdom's Heart",
    "Temple of Twilight",
    "Endless Abyss",
    "Serpent's Lair",
    "Celestial Chambers",
    "Forgotten Vale",
    "Chamber of the Ancients",
    "Stormshadow Ruins",
    "Ravine of the Lost",
    "Dreadhold Dungeon",
    "Dawn's End Crypt",
    "Caverns of Time",
    "Mystic Mountain Keep",
    "Realm of Shadows",
    "Desert's Whisper",
    "Frostfall Fortress",
    "Ruined Oasis",
    "Stonewrought Lair",
    "Abyssal Alcove",
    "Grove of Spirits",
    "Sunken Spire",
    "Eldritch Estate",
    "Void's Verge",
    "Horizon's Hold",
    "Sable Summit",
    "Forgotten Gorge",
    "Lost Sea Cave",
    "Grove of Desolation",
    "Endless Stair",
    "Temple of Dawn",
    "Nightsong Nook",
    "Molten Caverns",
    "Sun's Descent Grotto",
    "Vestige of the Ancients",
    "Hallowed Halls",
    "Mystic Canyons",
    "Undermountain Lair",
    "Ebon Enclave",
    "Whisperwind Keep",
    "Ivory Tower Ruins",
    "Guardian's Gorge",
    "Duskvale Dungeon",
    "Crystal Chasm",
    "Ruins of Reverie",
    "Twilight Terrace",
    "Starstruck Spire",
    "Cave of Solitude",
    "Silent Sentry Keep",
    "Emberhold",
    "Windswept Wastes",
    "Moonlit Grove",
    "Skyreach Citadel",
    "Shadowrift Sanctum",
    "Realm of Resurgence",
    "Ethereal Estate",
    "Blighted Bastion",
    "Ocean's Cry Grotto",
    "Elderwood Expanse",
    "King's Fall Fortress",
    "Temporal Tunnel",
    "Mystic Meadows",
    "Catacombs of Clarity",
    "Dread's Domain",
    "Solar Sanctuary",
    "Chamber of Chains",
    "Silverstrand Shore",
    "Bleakwood Bastion",
    "Cavern of Contemplation",
    "Frostvale Fortress",
    "Rivenrock Ruins",
    "Sanctuary of Sorrow",
    "Darkwater Depths",
    "Heaven's Fall Hollow"
]
