import type { Metadata } from 'next'
import Image from 'next/image'
import title from '@/public/hexquesttitle.webp'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function LoginLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <main className='h-[100dvh] w-full flex justify-center items-center'>
            <section className='mt-[15%]'>
                <Image src={title} alt={"hexagonal landscape"} fill />
                {children}
            </section>
        </main>
    )
}
