export const oceanNouns = [
    "Abyss",
    "Atoll",
    "Basin",
    "Bight",
    "Billow",
    "Brine",
    "Canyon",
    "Channel",
    "Chasm",
    "Cove",
    "Current",
    "Deep",
    "Delta",
    "Eddy",
    "Estuary",
    "Fathom",
    "Fjord",
    "Gulf",
    "Horizon",
    "Inlet",
    "Islet",
    "Jetstream",
    "Lagoon",
    "Maelstrom",
    "Narrows",
    "Ocean",
    "Passage",
    "Reef",
    "Ridge",
    "Ripple",
    "Salinity",
    "Seabed",
    "Seafloor",
    "Seamount",
    "Shoal",
    "Sound",
    "Strait",
    "Surf",
    "Swell",
    "Tide",
    "Trench",
    "Trough",
    "Undertow",
    "Upwelling",
    "Vortex",
    "Wave",
    "Whirlpool",
    "Riptide",
    "Thermocline",
    "Vents"
]

export const plainsNouns = [
    "Basin",
    "Bench",
    "Butte",
    "Chaparral",
    "Dale",
    "Depression",
    "Divide",
    "Dune",
    "Expanse",
    "Fallows",
    "Flatland",
    "Grassland",
    "Heath",
    "Highland",
    "Horizon",
    "Knoll",
    "Lowland",
    "Meadow",
    "Mesa",
    "Mire",
    "Moor",
    "Outwash",
    "Pampas",
    "Pasture",
    "Prairie",
    "Ravine",
    "Ridge",
    "Rise",
    "Savannah",
    "Scarp",
    "Steppe",
    "Tableland",
    "Tarn",
    "Terrace",
    "Tundra",
    "Upland",
    "Vale",
    "Valley",
    "Veld",
    "Vista",
    "Wash",
    "Wetland",
    "Wold",
    "Yield",
    "Zephyr",
    "Barrens",
    "Clearing",
    "Downs",
    "Escarpment"
]

export const hillNouns = [
    "Ascent",
    "Bank",
    "Bluff",
    "Brae",
    "Bump",
    "Butte",
    "Climb",
    "Crest",
    "Dale",
    "Decline",
    "Dell",
    "Down",
    "Drumlin",
    "Elevation",
    "Embankment",
    "Escarpment",
    "Expanse",
    "Fell",
    "Gradient",
    "Heath",
    "Highland",
    "Incline",
    "Knoll",
    "Ledge",
    "Mesa",
    "Mound",
    "Outcrop",
    "Peak",
    "Pinnacle",
    "Plateau",
    "Ravine",
    "Ridge",
    "Rise",
    "Slope",
    "Spur",
    "Summit",
    "Terrace",
    "Tor",
    "Upland",
    "Vale",
    "Valley",
    "Vista",
    "Wold",
    "Yawn",
    "Zigzag",
    "Bank",
    "Crag",
    "Declivity",
    "Eminence",
    "Foot"
]

export const mountainNouns = [
    "Alp",
    "Apex",
    "Arete",
    "Ascent",
    "Base",
    "Bluff",
    "Boulder",
    "Canyon",
    "Cirque",
    "Cliff",
    "Col",
    "Crag",
    "Crest",
    "Divide",
    "Escarpment",
    "Foothill",
    "Gorge",
    "Highland",
    "Hillside",
    "Incline",
    "Knoll",
    "Ledge",
    "Massif",
    "Notch",
    "Outcrop",
    "Peak",
    "Pinnacle",
    "Plateau",
    "Range",
    "Ravine",
    "Ridge",
    "Scarp",
    "Slope",
    "Spire",
    "Summit",
    "Terrace",
    "Tor",
    "Trench",
    "Upland",
    "Valley",
    "Vista",
    "Volcano",
    "Watershed",
    "Yawn",
    "Zigzag",
    "Blade",
    "Cleft",
    "Dell",
    "Elevation"
]

export const forestNouns = [
    "Arbor",
    "Bosk",
    "Canopy",
    "Dell",
    "Expanse",
    "Fernery",
    "Glen",
    "Hollow",
    "Interval",
    "Jungle",
    "Knick",
    "Lair",
    "Meadow",
    "Nook",
    "Orchard",
    "Paddock",
    "Quagmire",
    "Ravine",
    "Stand",
    "Thicket",
    "Underbrush",
    "Vale",
    "Woodland",
    "Xyloflora",
    "Yield",
    "Zone",
    "Brush",
    "Clearing",
    "Dense",
    "Edge",
    "Floor",
    "Grove",
    "Habitat",
    "Interior",
    "Jade",
    "Knot",
    "Layer",
    "Moss",
    "Nest",
    "Overgrowth",
    "Patch",
    "Quiet",
    "Root",
    "Shade",
    "Trail",
    "Understory",
    "Vista",
    "Wilderness",
    "Expanse"
]

export const desertNouns = [
    "Dune",
    "Oasis",
    "Butte",
    "Mesa",
    "Canyon",
    "Arroyo",
    "Salt flat",
    "Plateau",
    "Badland",
    "Ravine",
    "Gully",
    "Basin",
    "Escarpment",
    "Erg",
    "Hamada",
    "Wadi",
    "Playa",
    "Dry lake",
    "Rock formation",
    "Fossil bed",
    "Crevices",
    "Cliffs",
    "Hoodoo",
    "Gravel plain",
    "Interdune basin"
]

export const marshNouns = [
    "Bog",
    "Fen",
    "Mire",
    "Swale",
    "Tidal flat",
    "Slough",
    "Reedbed",
    "Mudflat",
    "Cattail stand",
    "Peatland",
    "Quagmire",
    "Sedge meadow",
    "Saltmarsh",
    "Brackish water",
    "Freshwater pool",
    "Wet prairie",
    "Hummock",
    "Mangrove",
    "Tussock",
    "Mud hole",
    "Estuary",
    "Bayou",
    "Creek bed",
    "Moss dome",
    "Sphagnum pool"
]

export const lakeNouns = [
    "Bay",
    "Island",
    "Inlet",
    "Tributary",
    "Delta",
    "Sandbar",
    "Reef",
    "Lagoon",
    "Jetty",
    "Water column",
    "Thermocline",
    "Lakebed",
    "Spring",
    "Estuary",
]

export const jungleNouns = [
    "Canopy",
    "Understory",
    "Forest floor",
    "Emergent layer",
    "Liana",
    "Bromeliad",
    "Mangrove swamp",
    "Waterfall",
    "Vine",
    "Buttress root",
    "Epiphyte",
    "Grove",
    "Riverbank",
    "Tributary",
    "Ravine",
    "Clearing",
    "Floodplain",
    "Lagoon",
    "Bamboo thicket",
    "Sinkhole",
]

export const coastNouns = [
    "Beach",
    "Cliff",
    "Dune",
    "Estuary",
    "Headland",
    "Lagoon",
    "Salt marsh",
    "Tidal pool",
    "Cove",
    "Bay",
    "Harbor",
    "Sea stack",
    "Peninsula",
    "Cape",
    "Shoal",
    "Reef",
    "Atoll",
    "Spit",
    "Ria",
    "Fjord",
    "Tidal flat",
    "Gulf",
    "Sound",
    "Mudflat"
]